version: '3.6'
services:
  postgres:
    image: postgis/postgis:15-3.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.36.0
    restart: always
    ports:
      - "8080:8080"
    # Remove dependency on local Postgres since Hasura will use Supabase instead
    # depends_on:
    #   - postgres
    environment:
      # Updated to use Supabase's connection string (with URL-encoded password and SSL required)
      HASURA_GRAPHQL_DATABASE_URL: "postgresql://postgres.aejfhbzodmxsgwugfagr:6jZJ6%26CYCAbvn%23x@aws-0-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: mysecret
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_DEV_MODE: "true"
      # Optionally disable prepared statements to avoid collision issues
      HASURA_GRAPHQL_DISABLE_PREPARED_STATEMENTS: "true"
      HASURA_GRAPHQL_PG_POOL_SETTINGS: '{"retries":1,"idle_timeout":180,"max_connections":10}'
      HASURA_GRAPHQL_JWT_SECRET: '{
              "type": "HS256",
              "key": "pcoaUQk4EKyF0BmVKD9Bmh+0Qhg1ZPE0OpIklZQTF68Sp3GyngO8gaJYCqcSFrB7iL2DYKwRI8uvyIq1GAjC/g==",
              "claims_namespace": "https://hasura.io/jwt/claims"
            }'
    volumes:
      - ./migrations:/migrations
      - ./metadata:/metadata

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
