app = "sidekick-dev-server"
primary_region = "bom"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  [services.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

[env]
  HASURA_GRAPHQL_DATABASE_URL = "postgresql://postgres.aejfhbzodmxsgwugfagr:6jZJ6%26CYCAbvn%23x@aws-0-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require"
  HASURA_GRAPHQL_ADMIN_SECRET = "mysecret"
  HASURA_GRAPHQL_ENABLE_CONSOLE = "true"
  HASURA_GRAPHQL_DEV_MODE = "true"
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE = "anonymous"
  HASURA_GRAPHQL_JWT_SECRET = "{\"type\": \"HS256\", \"key\": \"pcoaUQk4EKyF0BmVKD9Bmh+0Qhg1ZPE0OpIklZQTF68Sp3GyngO8gaJYCqcSFrB7iL2DYKwRI8uvyIq1GAjC/g==\", \"claims_namespace\": \"https://hasura.io/jwt/claims\"}"


